config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :sneakers, only: [:index, :show] do
    resources :collections, only: [:new, :create, :destroy, :update]
    resources :wishlists, only: [:new, :create, :destroy, :update]
  end
  get "wishlist", to: "dashboards#wishlist"
  get "collection", to: "dashboards#collection"
  get "profile", to: "dashboards#profile"
end

app/views/shared/_filter.html.erb
<h5>Brand</h5>
<div class="index-filter-brands mt-3 mb-3">
  <span data-action="click->filter#selectOption">Nike</span>
  <span data-action="click->filter#selectOption">Air Jordan</span>
  <span data-action="click->filter#selectOption">Adidas</span>
  <span data-action="click->filter#selectOption">New Balance</span>
  <span data-action="click->filter#selectOption">Reebok</span>
</div>
<h5>Price</h5>
<div class="index-filter-prices">
  <div class="range-slider">
    <span class="d-flex justify-content-between">
      <input type="number" value="0" min="0" max="10000" readonly/><i>€</i>
      <input type="number" value="5000" min="0" max="10000" readonly/><i>€</i>
    </span>
    <input value="0" min="0" max="10000" step="1" type="range"/>
    <input value="5000" min="0" max="10000" step="1" type="range"/>
  </div>
</div>
<h5>Sellers</h5>
<div class="d-flex justify-content-between index-filter-sellers mt-3 mb-5">
  <div>
    <span data-action="click->filter#selectOption">StockX</span>
    <span data-action="click->filter#selectOption">Wethenew</span>
    <span data-action="click->filter#selectOption">Klekt</span>
  </div>
  <button class="apply-filter-btn" type="submit" data-action="click->filter#submitFilter">Apply filter</button>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div>
    <%= link_to "Daily Sneakers", root_path, class: "footer-link" %>
  </div>
  <hr>
  <div class="container d-flex justify-content-between align-self-end">
    <div class="footer-copyright">
      © 2022 DailySneakers. All rights reserved - made with <i class="fas fa-heart"></i> at <a href="https://www.lewagon.com/fr">Le Wagon</a>
    </div>
    <div class="footer-links">
      <a href="#"><i class="fab fa-github"></i></a>
      <a href="#"><i class="fab fa-twitter"></i></a>
    </div>
  </div>
</div>

app/views/shared/_indexcard.erb
<div class="index-card col-3">
  <%= link_to sneaker_path(sneaker) do %>
    <div class="index-card-image" style="background-image: url('<%= sneaker.imgurl %>');">
      <% case sneaker.brand.downcase %>
      <% when 'nike' %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg" alt="" class="index-card-logo">
      <% when 'adidas' %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg" alt="" class="index-card-logo">
      <% when 'air jordan' %>
      <img src="https://upload.wikimedia.org/wikipedia/fr/3/37/Jumpman_logo.svg" alt="" class="index-card-logo">
      <% when 'new balance' %>
      <img src="https://www.logo.wine/a/logo/New_Balance/New_Balance-Logo.wine.svg" alt="" class="index-card-logo">
      <% when 'reebok' %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/5/53/Reebok_2019_logo.svg" alt="" class="index-card-logo">
      <% when 'puma' %>
      <img src="https://upload.wikimedia.org/wikipedia/fr/4/49/Puma_AG.svg" alt="" class="index-card-logo">
      <% when 'kangaroos' %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/b/be/Kangourou.svg" alt="" class="index-card-logo">
      <% when 'dior' %>
      <img src="https://upload.wikimedia.org/wikipedia/commons/a/a8/Dior_Logo.svg" alt="" class="index-card-logo">
      <% when 'nike sb' %>
      <img src="http://upload.wikimedia.org/wikipedia/commons/b/b2/Nike_sb_logo.png" alt="" class="index-card-logo">
    <% else %>
      <img src="" alt="" class="index-card-logo">
    <% end %>
    <div class="index-card-date">
      <%= sneaker.release.strftime("%m-%Y") %>
    </div>
  </div>
<% end %>
<div class="index-card-block">
  <h5><%= link_to "#{sneaker.brand} #{sneaker.model}", sneaker_path(sneaker) %></h5>
  <div class="index-card-bottom">
    <p class="index-card-price"><%= sneaker.prices.map { |i| i.price.to_i }.min %>€</p>
    <div class="index-card-shared">
      <i class="fa-solid fa-heart"></i>
      <i class="fa-solid fa-share-nodes"></i>
    </div>
  </div>
</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light fixed-top navbar-lewagon" data-controller="navbar" data-action="scroll@window->navbar#updateNavbar">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "https://res.cloudinary.com/beyonds-agency/image/upload/dpr_3.0,f_auto,q_auto,w_auto/v1/Projets/Opium/logo-opium", class:"logo" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="search-bar">
      <%= simple_form_for :search, url: sneakers_path, method: :get do |f| %>
        <div class="search-form-control form-group d-flex justify-content-between">
          <%= form_tag sneakers_path, method: :get, class:"mr-5" do %>
            <%= text_field_tag :search, params[:search], class: "form-control search-placeholder ", id: "search_query", placeholder: "Article name or keywords...", autocomplete: "off"%>
          <% end %>
          <button type="submit" class="button">
            Search
          </button>
        </div>
      <% end %>
    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <% if current_user.avatar.key.nil? %>
              <%= image_tag "https://thumbs.dreamstime.com/b/avatar-par-d%C3%A9faut-ic%C3%B4ne-profil-vectoriel-m%C3%A9dias-sociaux-utilisateur-portrait-176256935.jpg", class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% else %>
              <%= cl_image_tag current_user.avatar.key, class: "avatar-bordered dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% end %>
            <span class="dot-connected"></span>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Home", root_path, class: "dropdown-item" %>
              <%= link_to "Profile", profile_path, class: "dropdown-item" %>
              <%= link_to "Wishlist", wishlist_path, class: "dropdown-item" %>
              <%= link_to "Collection", collection_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item" %>
            </div>
          </li>
          <div class="nav-bar-user">
            <%= current_user.first_name %> <%= current_user.last_name %>
          </div>
        <% else %>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div class="nav-buttons d-flex justify-content-between">
              <%= link_to "Sign up", new_user_registration_path, class: "signup" %>
              <%= link_to "Log in", user_session_path, class: "login" %>
            </div>
          </div>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_sizer.html.erb
<div class="select-menu">
  <div class="select-btn">
    <span class="sBtn-text">Change size</span>
    <i class="bx bx-chevron-down"></i>
  </div>
  <ul class="options">
    <% hash.each do |k, v| %>
      <li class="option">
        <span class="option-text"><%= "US#{k}  #{v}€" %></span>
      </li>
    <% end %>
  </ul>
</div>