config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :sneakers, only: [:index, :show] do
    resources :collections, only: [:new, :create, :destroy, :update]
    resources :wishlists, only: [:new, :create, :destroy, :update]
  end
  get "wishlist", to: "dashboards#wishlist"
  get "collection", to: "dashboards#collection"
  get "profile", to: "dashboards#profile"
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def wishlist
    @sneaker = Wishlist.where(user: current_user)
    total = 0
    @sneaker.each do |sneaker|
      total += Price.where(sneaker: sneaker.sneaker).last.price
    end

    # Je sais c'est horrible mais j'ai pas l'time <3
    @month = Date.today.strftime("%B")
    @x_month = @month.to_time.last_month.strftime("%B")
    @xx_month = @x_month.to_time.last_month.strftime("%B")
    @xxx_month = @xx_month.to_time.last_month.strftime("%B")
    @xxxx_month = @xxx_month.to_time.last_month.strftime("%B")
    @xxxxx_month = @xxxx_month.to_time.last_month.strftime("%B")

    #create a function give a little variation up or down the price
    def variation(price)
      variation = rand(0..100)
      if variation > 5
        price += variation
      else
        price -= variation
      end
      return price
    end

    @total = total
    @x_total = variation(total)
    @xx_total = variation(@x_total)
    @xxx_total = variation(@xx_total)
    @xxxx_total = variation(@xxx_total)
    @xxxxx_total = variation(@xxxx_total)
  end

  def collection
    @sneaker = Collection.where(user: current_user)
    total = 0
    @sneaker.each do |sneaker|
      total += Price.where(sneaker: sneaker.sneaker).last.price
    end
    @total = total

    # Je sais c'est horrible mais j'ai pas l'time <3
    @month = Date.today.strftime("%B")
    @x_month = @month.to_time.last_month.strftime("%B")
    @xx_month = @x_month.to_time.last_month.strftime("%B")
    @xxx_month = @xx_month.to_time.last_month.strftime("%B")
    @xxxx_month = @xxx_month.to_time.last_month.strftime("%B")
    @xxxxx_month = @xxxx_month.to_time.last_month.strftime("%B")

    #create a function give a little variation up or down the price
    def variation(price)
      variation = rand(0..80)
      if variation > 5
        price += variation
      else
        price -= variation
      end
      return price
    end

    @total = total
    @x_total = variation(total)
    @xx_total = variation(@x_total)
    @xxx_total = variation(@xx_total)
    @xxxx_total = variation(@xxx_total)
    @xxxxx_total = variation(@xxxx_total)
  end

  def profile
  end
end

app/views/dashboards/collection.html.erb
<div class="container custom-margin">
  <div class="d-flex justify-content-between">
    <h4>My collection</h4>
    <div class="btn-group nav-dashboard" role="group" aria-label="Basic outlined example">
      <%= link_to 'Wishlist', wishlist_path, class: "btn btn-outline-secondary"%>
      <%= link_to 'Collection', collection_path, class: "btn btn-outline-secondary active"%>
      <%= link_to 'Profile', profile_path, class: "btn btn-outline-secondary"%>
    </div>
  </div>
  <h2>Real-time price: <%= @total %>€</h2>
  <div class="graph">
    <canvas
  data-controller="chart"
  data-chart-data-value='{ "labels": ["<%= @xxxxx_month%>", "<%= @xxxx_month%>", "<%= @xx_month%>", "<%= @x_month%>", "<%= @month%>"], "datasets": [{ "label": "My collection", "backgroundColor": "transparent", "borderColor": "#3B82F6", "data": [<%= @xxxx_total%>, <%= @xxx_total%>, <%= @xx_total%>, <%= @x_total%>, <%= @total%>] }] }'
></canvas>
  </div>
  <div class="d-flex mt-5">
    <h4>Sneakers</h4>
  </div>
  <div class="dashboard-table">
    <table class="table table-hover" data-controller='buyprice'>
      <thead>
        <tr>
          <th class="justify-text">Model</th>
          <th>Purchase price</th>
          <th>Size</th>
          <th>Actual price</th>
        </tr>
      </thead>
      <tbody>
        <% @sneaker.each do |snk| %>
          <tr>
            <td class="justify-text">
              <% case snk.sneaker.brand.downcase %>
              <% when 'nike' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg" alt="" class="index-card-logo">
              <% when 'adidas' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg" alt="" class="index-card-logo">
              <% when 'air jordan' %>
              <img src="https://upload.wikimedia.org/wikipedia/fr/3/37/Jumpman_logo.svg" alt="" class="index-card-logo">
              <% when 'new balance' %>
              <img src="https://www.logo.wine/a/logo/New_Balance/New_Balance-Logo.wine.svg" alt="" class="index-card-logo">
              <% when 'reebok' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/5/53/Reebok_2019_logo.svg" alt="" class="index-card-logo">
              <% when 'puma' %>
              <img src="https://upload.wikimedia.org/wikipedia/fr/4/49/Puma_AG.svg" alt="" class="index-card-logo">
              <% when 'kangaroos' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/b/be/Kangourou.svg" alt="" class="index-card-logo">
              <% when 'dior' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/a/a8/Dior_Logo.svg" alt="" class="index-card-logo">
              <% when 'nike sb' %>
              <img src="http://upload.wikimedia.org/wikipedia/commons/b/b2/Nike_sb_logo.png" alt="" class="index-card-logo">
            <% else %>
              <img src="" alt="" class="index-card-logo">
            <% end %> <%= snk.sneaker.brand %> <%= snk.sneaker.model %></td>
          <td>
            <% if snk.price_buy %>
              <%= snk.price_buy %>€
            <% else %>
              <p data-action='click->buyprice#addprice' class='btn-add-price'>Add price</p>
              <div class="add-price d-none">
                <%= simple_form_for [snk.sneaker, snk] do |f| %>
                  <%= f.input :price_buy, as: :integer, label: false %>
                <% end %>
              </div>
            <% end %>
          </td>
          <td><%= snk.size %></td>
          <td><%= snk.sneaker.prices.last.price %>€</td>
          <td>
            <%= link_to sneaker_collection_path(snk.id, Collection.find_by(user_id: current_user.id)), method: :delete do%>
              <i class="fas fa-trash-alt"></i>
            <% end %></td>
      </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/dashboards/profile.html.erb
<div class="container custom-margin">
  <div class="d-flex justify-content-between">
    <h4>My profile</h4>
    <div class="btn-group nav-dashboard" role="group" aria-label="Basic outlined example">
      <%= link_to 'Wishlist', wishlist_path, class: "btn btn-outline-secondary"%>
      <%= link_to 'Collection', collection_path, class: "btn btn-outline-secondary"%>
      <%= link_to 'Profile', profile_path, class: "btn btn-outline-secondary active"%>
    </div>
  </div>
  <div class="wrapper">
    <div class="profile-card js-profile-card">
      <div class="profile-card__img">
        <% if current_user.avatar.key.nil? %>
          <%= image_tag "https://thumbs.dreamstime.com/b/avatar-par-d%C3%A9faut-ic%C3%B4ne-profil-vectoriel-m%C3%A9dias-sociaux-utilisateur-portrait-176256935.jpg" %>
        <% else %>
          <%= cl_image_tag current_user.avatar.key %>
        <% end %>
      </div>
      <div class="profile-card__cnt js-profile-cnt">
        <div class="profile-card__name"> <%= current_user.first_name %> <%= current_user.last_name %></div>
        <div class="profile-card__txt">Your default sneaker size is  <strong><%= current_user.size %></strong></div>
        <div class="profile-card-inf">
          <div class="profile-card-inf__item">
            <div class="profile-card-inf__title"><%= Wishlist.where(user_id: current_user).length %></div>
            <div class="profile-card-inf__txt">Sneakers in your wishlist</div>
          </div>
          <div class="profile-card-inf__item">
            <div class="profile-card-inf__title"><%= Collection.where(user_id: current_user).length %></div>
            <div class="profile-card-inf__txt">Sneakers in your collection</div>
          </div>
        </div>
      </div>
      <%= link_to 'Edit', edit_user_registration_path(current_user), class: "button-edit-profil"%>
    </div>
  </div>
</div>

app/views/dashboards/wishlist.html.erb
<div class="container custom-margin" data-controller="wishlist">
  <div class="d-flex justify-content-between">
    <h4>My wishlist</h4>
    <div class="btn-group nav-dashboard" role="group" aria-label="Basic outlined example">
      <%= link_to 'Wishlist', wishlist_path, class: "btn btn-outline-secondary active"%>
      <%= link_to 'Collection', collection_path, class: "btn btn-outline-secondary"%>
      <%= link_to 'Profile', profile_path, class: "btn btn-outline-secondary"%>
    </div>
  </div>
  <h2>Actual value: <%= @total %>€</h2>
  <div class="graph">
    <canvas
  data-controller="chart"
  data-chart-data-value='{ "labels": ["<%= @xxxxx_month%>", "<%= @xxxx_month%>", "<%= @xx_month%>", "<%= @x_month%>", "<%= @month%>"], "datasets": [{ "label": "My wishlist", "backgroundColor": "transparent", "borderColor": "#3B82F6", "data": [<%= @xxxx_total%>, <%= @xxx_total%>, <%= @xx_total%>, <%= @x_total%>, <%= @total%>] }] }'
></canvas>
  </div>
  <div class="d-flex mt-5">
    <h4>Sneakers</h4>
  </div>
  <div class="dashboard-table" data-controller='alertprice'>
    <table class="table table-hover">
      <thead>
        <tr>
          <th class="justify-text">Model</th>
          <th>Expected price</th>
          <th>Release date</th>
          <th>Actual price</th>
        </tr>
      </thead>
      <tbody>
        <% @sneaker.each do |snk| %>
          <tr>
            <td class="justify-text">
              <% case snk.sneaker.brand.downcase %>
              <% when 'nike' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/a/a6/Logo_NIKE.svg" alt="" class="index-card-logo">
              <% when 'adidas' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/2/20/Adidas_Logo.svg" alt="" class="index-card-logo">
              <% when 'air jordan' %>
              <img src="https://upload.wikimedia.org/wikipedia/fr/3/37/Jumpman_logo.svg" alt="" class="index-card-logo">
              <% when 'new balance' %>
              <img src="https://www.logo.wine/a/logo/New_Balance/New_Balance-Logo.wine.svg" alt="" class="index-card-logo">
              <% when 'reebok' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/5/53/Reebok_2019_logo.svg" alt="" class="index-card-logo">
              <% when 'puma' %>
              <img src="https://upload.wikimedia.org/wikipedia/fr/4/49/Puma_AG.svg" alt="" class="index-card-logo">
              <% when 'kangaroos' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/b/be/Kangourou.svg" alt="" class="index-card-logo">
              <% when 'dior' %>
              <img src="https://upload.wikimedia.org/wikipedia/commons/a/a8/Dior_Logo.svg" alt="" class="index-card-logo">
              <% when 'nike sb' %>
              <img src="http://upload.wikimedia.org/wikipedia/commons/b/b2/Nike_sb_logo.png" alt="" class="index-card-logo">
            <% else %>
              <img src="" alt="" class="index-card-logo">
            <% end %> <%= snk.sneaker.brand %> <%= snk.sneaker.model %></td>
          <td>
            <% if snk.price_alert %>
              <%= snk.price_alert %>€
            <% else %>
              <p data-action='click->alertprice#addprice' class='btn-add-price'>Add price</p>
              <div class="add-price d-none">
                <%= simple_form_for [snk.sneaker, snk] do |f| %>
                  <%= f.input :price_alert, label: false %>
                <% end %>
              </div>
            <% end %>
          </td>
          <td><%= snk.sneaker.release %></td>
          <td><%= snk.sneaker.prices.last.price %>€</td>
          <td>
            <%= link_to sneaker_wishlist_path(snk.id, Wishlist.find_by(user_id: current_user.id)), method: :delete, remote: true do%>
              <i class="fas fa-trash-alt"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>