config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :sneakers, only: [:index, :show] do
    resources :collections, only: [:new, :create, :destroy, :update]
    resources :wishlists, only: [:new, :create, :destroy, :update]
  end
  get "wishlist", to: "dashboards#wishlist"
  get "collection", to: "dashboards#collection"
  get "profile", to: "dashboards#profile"
end

app/models/sneaker.rb
class Sneaker < ApplicationRecord
  paginates_per 20
  has_many :prices, dependent: :destroy
  validates :reference, presence: true, uniqueness: true
end

app/controllers/sneakers_controller.rb
class SneakersController < ApplicationController
  def index
    if params[:brands] != "" && params[:sellers] != "" && params[:brands] && params[:sellers]
      query = "brand IN ('#{params[:brands].gsub(",", "','")}')
        AND prices.market IN ('#{params[:sellers].gsub(",", "','")}')
        AND prices.price BETWEEN #{params[:min]} AND #{params[:max]}"
      @sneakers = Sneaker.joins(:prices).where(query).group(:id)
    elsif params[:brands] != "" && params[:brands]
      @sneakers = Sneaker.joins(:prices).where("brand IN ('#{params[:brands].gsub(",", "','")}')
        AND prices.price BETWEEN #{params[:min].to_i} AND #{params[:max].to_i}").group(:id)
    elsif params[:sellers] != "" && params[:sellers]
      @sneakers = Sneaker.joins(:prices).where("prices.market IN ('#{params[:sellers].gsub(",", "','")}')
        AND prices.price BETWEEN #{params[:min].to_i} AND #{params[:max].to_i}").group(:id)
    elsif params[:min] != "" && params[:min]
      @sneakers = Sneaker.joins(:prices).where("prices.price BETWEEN #{params[:min].to_i} AND #{params[:max].to_i}").group(:id)
    elsif params[:search]
      @sneakers = Sneaker.where("brand LIKE '%#{params[:search].capitalize}%' OR model LIKE '%#{params[:search].capitalize}%'")
    else
      @sneakers = Sneaker.all
    end
    @sneakers_page = Kaminari.paginate_array(@sneakers).page params[:page]
    @prices = Price.all
  end

  def show
    @sneaker = Sneaker.find(params[:id])
    @day = Date.today.strftime("%d/%m/%Y")
    @x_day = @day.to_time.prev_day.strftime("%d/%m/%Y")
    @xx_day = @x_day.to_time.prev_day.strftime("%d/%m/%Y")
    @xxx_day = @xx_day.to_time.prev_day.strftime("%d/%m/%Y")
    @xxxx_day = @xxx_day.to_time.prev_day.strftime("%d/%m/%Y")
    @xxxxx_day = @xxxx_day.to_time.prev_day.strftime("%d/%m/%Y")
    @xxxxxx_day = @xxxxx_day.to_time.prev_day.strftime("%d/%m/%Y")

    def price_random(sneaker_price)
      num = sneaker_price
      return rand(4) if num < 0.3
      return rand(6) if num < 0.7
      return rand(10) if num < 0.9
      return rand(30)
    end

    if params[:size]
      @total = Price.where(sneaker_id: params[:id], size: params[:size]).order(price: :asc).first.price
      @x_total = @total - price_random(@total) + price_random(@total)
      @xx_total = @x_total - price_random(@x_total) + price_random(@x_total)
      @xxx_total = @xx_total - price_random(@xx_total) + price_random(@xx_total)
      @xxxx_total = @xxx_total - price_random(@xxx_total) + price_random(@xxx_total)
      @xxxxx_total = @xxxx_total - price_random(@xxxx_total) + price_random(@xxxx_total)
    else
      @total = Price.where(sneaker_id: params[:id]).first.price
      @x_total = @total - price_random(@total) + price_random(@total)
      @xx_total = @x_total - price_random(@x_total) + price_random(@x_total)
      @xxx_total = @xx_total - price_random(@xx_total) + price_random(@xx_total)
      @xxxx_total = @xxx_total - price_random(@xxx_total) + price_random(@xxx_total)
      @xxxxx_total = @xxxx_total - price_random(@xxxx_total) + price_random(@xxxx_total)
    end
  end
end

app/views/sneakers/index.html.erb
<section data-controller="filter" class="container custom-margin">
  <div class="index-head mb-3">
    <% if @sneakers.count.is_a? Integer %>
      <h3> <%= @sneakers.count %> Results</h3>
    <% else %>
      <h3> <%= @sneakers.count.keys.count %> Results</h3>
    <% end %>
    <div class="d-flex justify-content-right">
      <% if params.keys.include?('min') && (params['max'].to_i < 10000) %>
        <span class="pillules price" data-action='click->filter#deletePrice'>Between <%= params['min'] %>$ and <%= params['max'] %>$</span>
      <% end %>
      <% if params.keys.include?('brands') %>
        <% params['brands'].split(',').each do |i| %>
          <span class="pillules" data-action='click->filter#deleteBrand'><%= i %></span>
        <% end %>
      <% end %>
      <% if params.keys.include?('sellers') %>
        <% params['sellers'].split(',').each do |i| %>
          <span class='pillules' data-action='click->filter#deleteSeller'><%= i %></span>
        <% end %>
      <% end %>
      <button data-action="click->filter#revealContent"><i class="fas fa-filter"></i>Filter</button>
    </div>
  </div>
  <div class="index-filter d-none" data-filter-target="content">
    <%= render 'shared/filter' %>
  </div>
</section>
<div class="container">
  <section class="row">
    <% @sneakers_page.each do |sneaker| %>
      <%= render 'shared/indexcard', sneaker: sneaker %>
    <% end %>
    <div class="index-pagination">
      <%= paginate @sneakers_page %>
    </div>
  </section>
</div>

app/views/sneakers/show.html.erb
<div class="container">
  <div class="show-page" data-controller="market">
    <div class="title pt-5">
      <h2 class="brand"><%= @sneaker.brand %> <%= @sneaker.model %></h2>
      <h4 class="my-3 color"><%= @sneaker.color %></h4>
    </div>
    <div class="header row">
      <div class="col-md-6 left-side">
        <img class="sneaker-img" src="<%= @sneaker.imgurl %>" alt="<%= @sneaker.brand %> <%= @sneaker.model %>">
      </div>
      <div class="col-md-6 right-side">
        <% dates = [] %>
        <% Price.where(sneaker_id: @sneaker.id).each do |i| %>
          <% dates << i.timestamp %>
        <% end %>
        <% if params['size'] %>
          <% size = params['size'] %>
        <% else %>
          <% size = Price.where(sneaker_id: @sneaker.id).first.size %>
        <% end %>
        <% infos = Price.where("sneaker_id = ? AND size = ? AND timestamp = ?",
        @sneaker.id, size, dates.max) %>
        <% hash = {} %>
        <% @sneaker.prices.each do |i| %>
          <% if hash[i.size] %>
            <% hash[i.size] > i.price ? hash[i.size] = i.price : nil %>
          <% else %>
            <% hash[i.size] = i.price %>
          <% end %>
        <% end %>
        <div class="best-price d-flex justify-content-between">
          <p class="price"><%= hash[size.to_f] %>€</p>
          <a class="market-btn" href="">
            <% case Price.where(sneaker_id: @sneaker.id, size: size, price: hash[size.to_f]).first.market %>
            <% when 'StockX' %>
            <%= image_tag "stockx.svg" %>
            <% when 'Klekt' %>
            <%= image_tag "klekt.png" %>
            <% when 'Wethenew' %>
            <%= image_tag "wethenew.png" %>
          <% else %>
            <%= image_tag "market.png" %>
          <% end %>
        </a>
      </div>
      <div class="information">
        <%= render 'shared/sizer', hash: hash, sneaker_id: @sneaker.id %>
        <p>Size: <strong>US<%= size %></strong></p>
        <p>Date: <strong><%= @sneaker.release %></strong></p>
        <p>Owners: <strong><%= Collection.where(sneaker_id: @sneaker.id).count %></strong></p>
        <div class="dash-buttons d-flex justify-content-between">
          <%= link_to sneaker_wishlists_path(@sneaker), method: :post, remote: true do %>
            <p class='wishlist'>Add to wishlist <i class="fa-solid fa-plus"></i></p>
          <% end %>
          <%= link_to sneaker_collections_path(@sneaker, size: size, prevPrice: @x_total), method: :post do %>
            <p class='collection'>Add to collection <i class="fa-solid fa-plus"></i></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="price-history pt-3 pb-5">
  <h4>Price history</h4>
  <div class="graph">
    <canvas
  data-controller="chart"
  data-chart-data-value='{ "labels": ["<%= @xxxxxx_day%>","<%= @xxxx_day%>", "<%= @xxx_day%>", "<%= @xx_day%>", "<%= @x_day%>", "<%= @day%>"], "datasets": [{ "label": "Prices", "backgroundColor": "transparent", "borderColor": "#3B82F6", "data": [<%= @xxxxx_total%>, <%= @xxxx_total%>, <%= @xxx_total%>, <%= @xx_total%>, <%= @x_total%>, <%= @total%>] }] }'
></canvas>
  </div>
</div>
<div class="dashboard-table mt-5 mb-5">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Reseller</th>
        <th>Actual price</th>
        <th>Latest update</th>
      </tr>
    </thead>
    <tbody>
      <% infos.each do |i| %>
        <tr>
          <td>
            <% case i.market %>
            <% when 'StockX' %>
            <%= image_tag "stockx.svg" %>
            <% when 'Klekt' %>
            <%= image_tag "klekt.png" %>
            <% when 'Wethenew' %>
            <%= image_tag "wethenew.png" %>
          <% else %>
            <%= image_tag "market.png" %>
          <% end %>
        </td>
        <td><%= i.price %>€</td>
        <td><%= i.timestamp %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>